window:
  board_position: [200, 310]
  board_size: [160, 352]
  next_position: [249, 281]
  next_size: [60, 23]

puzzle_chip:
  size: [16, 16]

suppress_num: 5 # for suppress continuously fire check_next() in captute_bombliss.py

directory_next_imgs: "next_imgs_bombrite/"

tetriminos:
  I:
    identifier:
      - "I"
    align: [3, 5]
    form:
      -
        - [1, 1, 1, 1]
      -
        - [1]
        - [1]
        - [1]
        - [1]

  Z:
    identifier:
      - "Z"
    align: [3, 3]
    form:
      -
        - [1, 1, 0]
        - [0, 1, 1]
      -
        - [0, 1]
        - [1, 1]
        - [1, 0]

  J:
    identifier:
      - "J"
    align: [3, 3, 3, 4]
    form:
      -
        - [1, 1, 1]
        - [0, 0, 1]
      -
        - [0, 1]
        - [0, 1]
        - [1, 1]
      -
        - [1, 0, 0]
        - [1, 1, 1]
      -
        - [1, 1]
        - [1, 0]
        - [1, 0]

  O:
    identifier:
      - "O"
    align: [4]
    form:
      -
        - [1, 1]
        - [1, 1]

  S:
    identifier:
      - "S"
    align: [3, 3]
    form:
      -
        - [0, 1, 1]
        - [1, 1, 0]
      -
        - [1, 0]
        - [1, 1]
        - [0, 1]

  T:
    identifier:
      - "T"
    align: [3, 3, 3, 4]
    form:
      -
        - [1, 1, 1]
        - [0, 1, 0]
      -
        - [0, 1]
        - [1, 1]
        - [0, 1]
      -
        - [0, 1, 0]
        - [1, 1, 1]
      -
        - [1, 0]
        - [1, 1]
        - [1, 0]

  L:
    identifier:
      - "L"
    align: [3, 3, 3, 4]
    form:
      -
        - [1, 1, 1]
        - [1, 0, 0]
      -
        - [1, 1]
        - [0, 1]
        - [0, 1]
      -
        - [0, 0, 1]
        - [1, 1, 1]
      -
        - [1, 0]
        - [1, 0]
        - [1, 1]

  I2:
    identifier:
      - "I2"
    align: [3, 5]
    form:
      -
        - [1, 1, 1, 1]
      -
        - [1]
        - [1]
        - [1]
        - [1]

  Z2:
    identifier:
      - "Z2"
    align: [3, 3]
    form:
      -
        - [1, 1, 0]
        - [0, 1, 1]
      -
        - [0, 1]
        - [1, 1]
        - [1, 0]

  J2:
    identifier:
      - "J2"
    align: [3, 3, 3, 4]
    form:
      -
        - [1, 1, 1]
        - [0, 0, 1]
      -
        - [0, 1]
        - [0, 1]
        - [1, 1]
      -
        - [1, 0, 0]
        - [1, 1, 1]
      -
        - [1, 1]
        - [1, 0]
        - [1, 0]

  O2:
    identifier:
      - "O2"
    align: [4]
    form:
      -
        - [1, 1]
        - [1, 1]

  S2:
    identifier:
      - "S2"
    align: [3, 3]
    form:
      -
        - [0, 1, 1]
        - [1, 1, 0]
      -
        - [1, 0]
        - [1, 1]
        - [0, 1]

  T2:
    identifier:
      - "T2"
    align: [3, 3, 3, 4]
    form:
      -
        - [1, 1, 1]
        - [0, 1, 0]
      -
        - [0, 1]
        - [1, 1]
        - [0, 1]
      -
        - [0, 1, 0]
        - [1, 1, 1]
      -
        - [1, 0]
        - [1, 1]
        - [1, 0]

  L2:
    identifier:
      - "L2"
    align: [3, 3, 3, 4]
    form:
      -
        - [1, 1, 1]
        - [1, 0, 0]
      -
        - [1, 1]
        - [0, 1]
        - [0, 1]
      -
        - [0, 0, 1]
        - [1, 1, 1]
      -
        - [1, 0]
        - [1, 0]
        - [1, 1]
