window:
  board_position: [1308, 273]
  board_size: [270, 528]
  next_position: [1391, 233]
  next_size: [100, 30]

puzzle_chip:
  size: [27, 24]

directory_next_imgs: "next_imgs/"

tetrimino_pattern: "TETRIMINOS_Bombliss"

tetriminos:
  I:
    identifier:
      - "I"
    align: [3, 5]

  Z:
    identifier:
      - "Z"
    align: [3, 3]

  J:
    identifier:
      - "J"
    align: [3, 3, 3, 4]

  O:
    identifier:
      - "O"
    align: [4]

  S:
    identifier:
      - "S"
    align: [3, 3]

  T:
    identifier:
      - "T"
    align: [3, 3, 3, 4]

  L:
    identifier:
      - "Z"
    align: [3, 3, 3, 4]

  LJ:
    identifier:
      - "LJ"
    align: [4, 3, 3, 4]

  O1:
    identifier:
      - "O1"
    align: [3, 3, 3, 4]

  L1:
    identifier:
      - "L1"
    align: [3, 4, 3, 4]

  J1:
    identifier:
      - "J1"
    align: [3, 4, 3, 4]

  I1:
    identifier:
      - "I1"
    align: [3, 4]

  I2:
    identifier:
      - "I2"
    align: [2, 4]

  O2:
    identifier:
      - "O2"
    align: [3, 3, 3, 4]
